Fix small problems in use_case test
RaghavAtRuntime/wordle-clone pull request #82
Opened 2024-12-02 23:30 UTC by CaaarolXu

Presently,
- Fix the problems that appeared in the tests. Now all tests should pass.
- Add one more test in LoginInteractorTest for coverage.
- Add one comment to SignupInteractorTest for how to use this test.

2024-12-03 02:03 UTC, RaghavAtRuntime submitted a review, later dismissed
Fixes bugs in tests. Great!

2024-12-03 09:40 UTC, CaaarolXu commented
Update for test coverage. Still waiting for the connection to check some tests.

2024-12-03 21:58 UTC, majidism006 approved these changes, later dismissed
Perfect! Im glad the tests are complete!

2024-12-03 22:54 UTC, RaghavAtRuntime approved these changes, later dismissed

2024-12-03 23:25 UTC, ibrmaj approved these changes, later dismissed

2024-12-03 23:28 UTC, majidism006 commented on src/main/java/app/AppBuilder.java
> +        cardPanel.setPreferredSize(new Dimension(WIDTH, HEIGHT));
Thanks for creating the private static variables for the dimensions width and height, code looks alot cleaner now!

2024-12-04 00:30 UTC, ibrmaj requested changes

2024-12-04 00:30 UTC, ibrmaj commented on src/test/java/use_case/DiscussionInteractorTest.java
> +        DiscussionPostViewModel viewModel = new DiscussionPostViewModel();
When naming viewModel name it discussionViewModel for better readibilty

2024-12-04 00:30 UTC, ibrmaj commented on src/test/java/use_case/DiscussionInteractorTest.java
> +    @Test
please add a small description of what each test is testing

2024-12-04 00:30 UTC, ibrmaj commented on src/test/java/use_case/HistoryInteractorTest.java
> +    public static final String TEXT2 = "another text for testing";
Change variable name to be more specific

2024-12-04 00:30 UTC, ibrmaj commented on src/test/java/use_case/InstructionsInteractorTest.java
> +
small description for the test please

2024-12-04 03:53 UTC, majidism006 submitted a review, later dismissed

2024-12-04 03:53 UTC, majidism006 commented on src/test/java/use_case/DiscussionInteractorTest.java
> +    //TODO: check after connection works
I believe the connection to the database has resumed. Is it possible to update this comment now?

2024-12-04 21:36 UTC, ibrmaj approved these changes

2024-12-04 21:37 UTC, majidism006 approved these changes

2024-12-04 21:37 UTC, merged