New and final updates
RaghavAtRuntime/wordle-clone pull request #83
Opened 2024-12-03 22:23 UTC by majidism006

Here are some new and final updates guys! Go team!

2024-12-03 22:55 UTC, RaghavAtRuntime submitted a review, later dismissed
Great job cleaning up the code.

2024-12-03 23:30 UTC, ibrmaj requested changes

2024-12-03 23:30 UTC, ibrmaj commented on src/main/java/use_case/grid/GridInputData.java
> -     * (Currently returns an empty string, to be implemented)
Please add JavaDoc related to the method

2024-12-03 23:30 UTC, ibrmaj commented on src/main/java/view/InstructionsView.java
>      private JPanel createExample(String word, int highlightedIndex) {
this is not really java doc its more like a comment, what you had up there in SwitchToProfileView is proper JavaDoc

2024-12-03 23:30 UTC, ibrmaj commented on src/main/resources/easy_words
> +STEEL
Words are not really easy, should have used the website linked on discord for easier words, I would suggest move more of these to the hard_words file

2024-12-03 23:30 UTC, ibrmaj commented on src/main/java/use_case/instructions/InstructionsInteractor.java
> +     * Switches to Profile View.
Good JavaDoc!

2024-12-03 23:31 UTC, majidism006 commented on src/main/java/use_case/instructions/InstructionsInteractor.java
> +     * Switches to Profile View.
Thank you!

2024-12-03 23:32 UTC, ibrmaj commented
Nice refactoring, maybe a bit more cleanup would help, I have added the needed things that should be resolved!

2024-12-03 23:48 UTC, ibrmaj approved these changes

2024-12-03 23:48 UTC, ibrmaj commented
Good Job!

2024-12-04 00:32 UTC, CaaarolXu requested changes

2024-12-04 00:32 UTC, CaaarolXu commented on src/main/java/use_case/grid/GridInputData.java
>      public String getGuess() {
This method is duplicated by getLetter(). Please delete one of them.

2024-12-04 00:32 UTC, CaaarolXu commented on src/main/java/use_case/grid/GridInputData.java
>      public String getGuess() {
getLetter() is never used, so I think we can delete it.

2024-12-04 03:31 UTC, CaaarolXu approved these changes

2024-12-04 03:31 UTC, merged